### PR TITLE
Add note to mention adding event listeners that need to call C# methods

### PR DESCRIPTION
**Pull request by chassq**
Added this to learn blazor docs. See https://learn-blazor.com/architecture/interop/ . So thought about adding it here as well.

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks for the submission @chassq. I'll make some small changes to the text to conform to MS guidelines after we hear back from engineering.

**Comment by guardrex** [comment]
@chassq Do you want to update the PR for 0.5.0?

**Comment by guardrex** [comment]
@danroth27 Should this be closed, or should I work the concepts in the PR forward for the latest JS interop bits?

**Comment by danroth27** [comment]
I think we can just close this one.

**Pull request closed without merging**
