### PR TITLE
Added instructions to host in SharePoint Online.

### PR DESCRIPTION
**Pull request by kurtnelle**
I added instructions on Hosting in SharePoint Online.

### CODE REVIEW

**Comment by guardrex** [comment]
Thanks for the contribution @kurtnelle. I'll review this soon and make a few grammar+style guidelines updates before pinging engineering for review.

**Comment by guardrex** [comment]
Buried in work. 🏃 Let's make sure it's conceptually approved by engineering first, then I'll patch it up a bit.

**Comment by kurtnelle** [comment]
Kewlio.

**Comment by danroth27** [comment]
@kurtnelle Thank you for this contribution. While deploying Blazor apps to SharePoint Online is an interesting scenario, it's not within the scope of scenarios that we are seeking to document in the official Blazor docs at this time, so I'm going to go ahead and close this PR.

**Pull request closed without merging**
