### PR TITLE
Added Blazor Extensions org link

### PR DESCRIPTION
**Pull request by galvesribeiro**

### CODE REVIEW

**Comment by galvesribeiro** [comment]
@danroth27 I can change that. But just as a note, yes, maybe we will have more libraries there which are 100% C#-based. For now, we are investing time on JS interop to fill the gap on APIs missing on Blazor.

Do you want me to change it to just "Libraries"?

**Comment by guardrex** [comment]
The change was already made on #116 ... I was just waiting for final approval on it.

**Comment by danroth27** [comment]
:+1:

**Comment by guardrex** [comment]
Thanks @galvesribeiro! :rocket:

I resolved the conflict and alphabetized the list.

**Pull request merged**
