### PR TITLE
Blazor Asteroids added to community.md samples

### PR DESCRIPTION
**Pull request by aesalazar**
Add Blazor Asteroids sample, alphabetically.

repo: https://github.com/aesalazar/AsteroidsWasm/
demo: https://aesalazar.github.io/AsteroidsWasm/

### CODE REVIEW

**Comment by guardrex** [comment]
@danroth27 Sorry to have to tell you this based on @aesalazar's app here ... but my productivity on the docs **_just went right down the drain!_** :smile: lol

Great job @aesalazar! ... This is my new favorite Blazor app! :tada:

**Comment by guardrex** [comment]
Another note @aesalazar ...

capture

When you get up to the very high scores ... many *roids* on the playing field ... the algorthym that tries not to plop you down right in a glide path takes several minutes to put your next ship out. You might want to just have a spacebar-appear option for the player in case they don't want to wait any longer.

Again, nice job on this! *LoVe It!* ........... ok .... *now back to **real** work!* ⛏

**Comment by danroth27** [comment]
I sent a [PR](https://github.com/aesalazar/AsteroidsWasm/pull/1) to at least get the game to render in Edge, but keyboard controls don't seem to work. Might be related to https://github.com/aspnet/Blazor/issues/1290.

**Comment by aesalazar** [comment]
@guardrex LOL  Thats some score.  I will create a ticket for myself for the space bar idea.  That will take a little effort.  Nothing terrible but not a 5 min thing.

@danroth27 Thanks for the PR to fix the Edge error.  For the keyboards, it looks like the trick to use tabindex="-1" so I can do blazor-side Key Up/Down event handlers doesnt work in Edge :/.  Looks like I will have to go back to Interop.  Should be easy enough to revert.

**Comment by guardrex** [comment]
> Thats some score

I have quite a bit of experience. I mean I played **_A LOT_** of Asteroids ... for real ......

"for real" ....... as in I played it **_in an arcade when it came out in 1979!_** *Yikes!* lol 👴

**Comment by aesalazar** [comment]
@danroth27 Ok, updated the demo and seems to be fully working in Edge for me:

**Comment by aesalazar** [comment]
@guardrex  That is slightly before my time.  I started playing it in the 80's on Atari 👍

**Comment by guardrex** [comment]
One other thing ... it loads to say "Game Over" ... there's no indication that the player should tap an arrow key to get the game started.

btw -- Tweeted it, too. https://twitter.com/guardrex/status/1050733255102816257

Next??!! ... *Blazor Missile Command* ?????

**Comment by aesalazar** [comment]
@guardrex :
https://www.c-sharpcorner.com/article/missile-command-net/

Totally!!!!

**Pull request merged**
